### ISSUE TITLE
Make sure no Dockerfiles are missing an entrypoint

### ISSUE THREAD

**Issue by syreal17** [picoCTF/start-problem-dev#4]
Custom cmgr challenges need an entrypoint to avoid containers falling into a start/restart loop. Check that my example Dockerfiles here have that, like:

https://github.com/picoCTF/challenges/blob/main/cmgr/picoctf-2023/General%20Skills/rules-2023/Dockerfile

**Comment by syreal17** [comment]
Does this problem need a CMD instruction?

https://github.com/picoCTF/start-problem-dev/blob/master/example-problems/custom-web/Dockerfile

**Comment by dmartin** [comment]
> Does this problem need a CMD instruction?
> 
> https://github.com/picoCTF/start-problem-dev/blob/master/example-problems/custom-web/Dockerfile

I don’t think so, it’ll use the base `nginx` image’s entrypoint. It usually comes up as an problem with OS (rather than application) base images since their CMD is usually just a shell.
